### PR TITLE
main changes into config

### PR DESCRIPTION
**Pull request by poer-sophia**

### CODE REVIEW

**Comment by colindaven** [comment]
Hi, why did you close this, is it not ready ? 
I am not ready with the Wochenende config branch integration into dev. We have to warn Ilona that things will fall apart too, so not to upgrade for a few days.

**Comment by poer-sophia** [comment]
Yes, I just wanted some changes I made to the dev and main branch to be in the config branch as well so I wanted to merge main into dev. But when I wanted to merge a warnig massage appears that I would do change to main or something like that. It sounded like I would do something to the main branch. But I didnt want that so I just closed the PR again.

**Comment by colindaven** [comment]
yeah that was the same situation I had. I created a temporary branch to add the changes to so I wouldn't change main. Worked fine then.

**Comment by poer-sophia** [comment]
ahh okay i will try this too

**Pull request closed without merging**
