### PR TITLE
scripts to create heattrees in R from haybaler output

### PR DESCRIPTION
**Pull request by poer-sophia**
The first script to use heattrees. 
The bash scripts prepares the files for R, starts the create_heattrees_R script and later moves the heatmaps in created directories. Heattrees are created for RPMM and bacteria_per_human_cell files. 3 types of heattrees are createt: 

- One with the sums for all samples
- One for each sample in teh files
- One for each sample but with the sums form all sample s as background

Copy both scripts in haybaler_output on hpc-bc15-07 and run the run_heattrees.R script to test them. 

The create_heattrees_metadata.R script is more like a template if someone wants to plot a heattree with metadata. It is not really automated and a few things need to be edited or prepared for different metadata. 

Ilona is now starting to test the scripts to find bugs and give feedback for more/better functions.

### CODE REVIEW

**Comment by colindaven** [comment]
Very nice. We should correct the typo in the metadata filename. Am just testing now.
create_heattrees_metadate.R
-> create_heattrees_metadata.R

**Comment by poer-sophia** [comment]
Oh yes of course, I often don´t see typos

**Comment by colindaven** [comment]
hmm, some files are missing. It's installed R dependencies now.
 
```
INFO: run this script only on hpc-bc15-07!
INFO: Preparing files for R heatmap creation
Running on  RPMM*haybaler_taxa.csv
grep: RPMM*haybaler_taxa.csv: No such file or directory
Running on  bacteria_per_human_cell*haybaler_taxa.csv
grep: bacteria_per_human_cell*haybaler_taxa.csv: No such file or directory
```

**Comment by poer-sophia** [comment]
Do  you mean that it only runs on RPMM and bacteria_per_human_cell files? That is purposly. It doesnt really makes sense to plot the other files too. 

Or do you mean that the files are not found/not there? Have you run the haybaler_taxonomy.R script before? The haybaler_taxa.csv need to be createt at first. I forgot to  mention that.

**Comment by colindaven** [comment]
Yeah, all of the above. Looks nice now though. I adapter Wochenende postprocess to pick up the new scripts. 

Good job

**Comment by poer-sophia** [comment]
Okay thank you. But the script just works on hpc-bc15-07 so then it would only be possible to run the postprocess script on that server. Is there a way to check on which server the script is running so it only tries to make heattrees on that specific Server?

**Comment by colindaven** [comment]
something like

.... but .... what is necessary to run heat trees. Please document this :-) (next week),
cheers

```

#!/bin/bash


if [[ $(hostname) == "hpc-bc15-07" ]]
        then
        echo "INFO: Found hostname hpc-bc15-07. We can run heat trees here!"
else
                echo "INFO: Can only run heat trees on server where XXXXXXXXXXx is installed (hpc-bc15-07). We can't run heat trees here!"
fi





```

**Pull request merged**
