### PR TITLE
Works for haybaler output. Reference testing Mode. More filtering

### PR DESCRIPTION
**Pull request by poer-sophia**
Works with haybler output as input. Saves a new csv with the genus as new column. For now the column with the actual reference names is still there. 
Two more filter steps to work with a few more references (eg. no TPA more as genus)
Added Mode for Reference testing. 
Remove a few comments which were just for testing.

### CODE REVIEW

**Comment by colindaven** [comment]
OK, good, it runs. Thanks.

But the genus column is weird. Some are very incorrect. Eg on our haybaler control_data in the repo

```
# all should be Unknown - or what do you suggest?
1_1_1_2                                                                                                                    chr2
1_CP006958_1_UNVERIFIED__Achromobacter_xylosoxidans_NBRC_15126___ATCC_27061__complete_genome_BAC                           UNVERIFIED
```        
Do you think 1_1_1 should just be read to be Homo (Homo sapiens chr1). .... ?

**Comment by poer-sophia** [comment]
For some reason "UNKOWN" is a species with a TaxID in NCBI so I didnt get NAN values with name2taxid and counted "UNKNOWN" species as worked. With "NOT KNOWN" name2taxid gives NAN for genus and taxid so they are counted as "dont work"

**Comment by poer-sophia** [comment]
> OK, good, it runs. Thanks.
> 
> But the genus column is weird. Some are very incorrect. Eg on our haybaler control_data in the repo
> 
> ```
> # all should be Unknown - or what do you suggest?
> 1_1_1_2                                                                                                                    chr2
> 1_CP006958_1_UNVERIFIED__Achromobacter_xylosoxidans_NBRC_15126___ATCC_27061__complete_genome_BAC                           UNVERIFIED
> ```
> 
> Do you think 1_1_1 should just be read to be Homo (Homo sapiens chr1). .... ?

Yes so the 1_1_1 should be read as homo sapiens, I guess that would work best. And for now the organisms which produce NAN values with pytaxonkit are not filtered out yet. So yes they should be UNKNOWN or NOT KNOWN. I will work on this now.

**Comment by poer-sophia** [comment]
Now 1_1_1 has "homo sapiens" as genus. Or should I better put just "homo" as genus because "homo sapiens" is a species and "homo" is the correct genus? 
And every name that produces NAN values is now "NOT KNOWN".
I also added a little bit code in the save_csv function to check if the name of the input file contains a "haybaler", otherwise this file gets overwritten by the output because there is no "haybaler" to replace in the name. Now there is a error message instead and the system exits.

**Comment by colindaven** [comment]
Thanks Sophia!
Just Homo would be better if we're looking at genera. Thanks.
In a meeting, will test this after.
Great, avoiding overwriting data is very good practice....

**Review by colindaven — APPROVED** [review]

**Pull request merged**
