### PR TITLE
lineage for genus

### PR DESCRIPTION
**Pull request by poer-sophia**
new function to find the lineage for genus and then try to filter out which lineage is the right one if a name has multiple taxIDs assigned to it. 

Still needs improvement and testing for more references but seems to work for the newest reference.

### CODE REVIEW

**Comment by colindaven** [comment]
I'm still getting this error:

```
(haybaler) rcug@hpc06:/ngsssd1/rcug/wochenende_test/haybaler_tax$ bash run_haybaler_tax.sh
Starting Haybaler taxonomy
Traceback (most recent call last):
  File "haybaler_taxonomy.py", line 240, in <module>
    main()
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "haybaler_taxonomy.py", line 210, in main
    csv.insert(loc=0, column='genus', value=genus_series.values)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/pandas/core/frame.py", line 3760, in insert
    self._mgr.insert(loc, column, value, allow_duplicates=allow_duplicates)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1191, in insert
    raise ValueError(f"cannot insert {item}, already exists")
ValueError: cannot insert genus, already exists


I also, logically, get this when using the direct command listed in haybaler_taxonomy.py itself, not the bash script 

(haybaler) rcug@hpc06:/ngsssd1/rcug/wochenende_test/haybaler_tax$ python3 haybaler_taxonomy.py  -i 2021_02_human_bact_fungi_vir_masked.fa.fai -p /lager2/rcug/seqres/metagenref/

Traceback (most recent call last):
  File "haybaler_taxonomy.py", line 240, in <module>
    main()
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "haybaler_taxonomy.py", line 210, in main
    csv.insert(loc=0, column='genus', value=genus_series.values)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/pandas/core/frame.py", line 3760, in insert
    self._mgr.insert(loc, column, value, allow_duplicates=allow_duplicates)
  File "/mnt/ngsnfs/tools/miniconda3/envs/haybaler/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1191, in insert
    raise ValueError(f"cannot insert {item}, already exists")
ValueError: cannot insert genus, already exists


```

**Review by poer-sophia — COMMENTED** [review]
oh yes of course, thanks

**Comment by poer-sophia** [comment]
Okay I am going to look why this is still happening, when I tried it the last time everything worked fine.

**Comment by poer-sophia** [comment]
I know that I accidently had a line of code in a previous version that saved the inserted genus column in the input fai file. When the fai file is read in the next time you run the code, the inserted column is already in the file and then can't be inserted again. 

I deleted the line that saved the file with the inserted column but if the column is still in the input fai,  the error also still occures.

**Comment by colindaven** [comment]
Ah, good find. The input file has been changed : thanks:


```
1_1_1_10        genus   133797422       10      60      61
1_1_1_11        chr11   135086622       136027400       60      61

```

**Comment by colindaven** [comment]
I'm now getting the save file error:

`python3 haybaler_taxonomy.py  -i 2021_02_human_bact_fungi_vir_masked.fa.fai -p /lager2/rcug/seqres/metagenref/
`
ERROR: Input file 2021_02_human_bact_fungi_vir_masked.fa.fai has an incompatible file name. Needs a *haybaler.csv as input otherwise the inputfile gets overwritten.

**Comment by poer-sophia** [comment]
Okay, at the moment the input file should never be overwritten, because either I change the name so a differnt file is created to save the output or the error you got occures to prevent this. 

I guess the test_reference variable is False? Because if it is true it should not even try to save the file again.  I should maybe put that as an information in the error massage.

```
def save_csv(csv, path, name):
    if "haybaler" in name:
        csv.to_csv(path + "/" + name.replace("haybaler", "haybaler_genus"), sep="\t")
    else:
        sys.exit("ERROR: Input file {} has an incompatible file name. Needs a *haybaler.csv as input otherwise the "
                 "inputfile gets overwritten.".format(name))
```

**Pull request merged**
